//
//  WordBank.swift
//  sbtraining
//
//  Created by Eric Hernandez on 2/9/19.
//  Copyright © 2019 Eric Hernandez. All rights reserved.
//

import Foundation
class WordBank{
    
    var list = [Word]()
    
    init(){
        list.append(Word(word:"Ba"))
        list.append(Word(word:"Bé"))
        list.append(Word(word:"Bi"))
        list.append(Word(word:"Bó"))
        list.append(Word(word:"Bu"))
        list.append(Word(word:"Da"))
        list.append(Word(word:"Dé"))
        list.append(Word(word:"Di"))
        list.append(Word(word:"Dó"))
        list.append(Word(word:"Du"))
        list.append(Word(word:"Ha"))
        list.append(Word(word:"Hé"))
        list.append(Word(word:"Hi"))
        list.append(Word(word:"Hó"))
        list.append(Word(word:"Hu"))
        list.append(Word(word:"Ja"))
        list.append(Word(word:"Jé"))
        list.append(Word(word:"Ji"))
        list.append(Word(word:"Jó"))
        list.append(Word(word:"Ju"))
        list.append(Word(word:"Ka"))
        list.append(Word(word:"Ké"))
        list.append(Word(word:"Ki"))
        list.append(Word(word:"Kó"))
        list.append(Word(word:"Ku"))
        list.append(Word(word:"La"))
        list.append(Word(word:"Lé"))
        list.append(Word(word:"Li"))
        list.append(Word(word:"Ló"))
        list.append(Word(word:"Lu"))
        list.append(Word(word:"Ma"))
        list.append(Word(word:"Mé"))
        list.append(Word(word:"Mi"))
        list.append(Word(word:"Mó"))
        list.append(Word(word:"Mu"))
        list.append(Word(word:"Na"))
        list.append(Word(word:"Né"))
        list.append(Word(word:"Ni"))
        list.append(Word(word:"Nó"))
        list.append(Word(word:"Nu"))
        list.append(Word(word:"Pa"))
        list.append(Word(word:"Pé"))
        list.append(Word(word:"Pi"))
        list.append(Word(word:"Pó"))
        list.append(Word(word:"Pu"))
        list.append(Word(word:"Ra"))
        list.append(Word(word:"Ré"))
        list.append(Word(word:"Ri"))
        list.append(Word(word:"Ró"))
        list.append(Word(word:"Ru"))
        list.append(Word(word:"Sa"))
        list.append(Word(word:"Sé"))
        list.append(Word(word:"Si"))
        list.append(Word(word:"Só"))
        list.append(Word(word:"Su"))
        list.append(Word(word:"Ta"))
        list.append(Word(word:"Té"))
        list.append(Word(word:"Ti"))
        list.append(Word(word:"Tó"))
        list.append(Word(word:"Tu"))
        list.append(Word(word:"Va"))
        list.append(Word(word:"Vé"))
        list.append(Word(word:"Vi"))
        list.append(Word(word:"Vó"))
        list.append(Word(word:"Vu"))
        list.append(Word(word:"Wa"))
        list.append(Word(word:"Wé"))
        list.append(Word(word:"Wi"))
        list.append(Word(word:"Wó"))
        list.append(Word(word:"Wu"))
        list.append(Word(word:"Ya"))
        list.append(Word(word:"Yé"))
        list.append(Word(word:"Yi"))
        list.append(Word(word:"Yó"))
        list.append(Word(word:"Yu"))
        list.append(Word(word:"Za"))
        list.append(Word(word:"Zé"))
        list.append(Word(word:"Zi"))
        list.append(Word(word:"Zó"))
        list.append(Word(word:"Zu"))
    }
}
